site_name: Concerns on the use of generative AI in research

theme:
  name: material
  custom_dir: overrides
  logo: assets/logo.png
  palette:
    primary: indigo

extra_css:
  - stylesheets/extra.css

plugins: []
