site_name: Concerns on the use of generative AI in research

theme:
  name: material
  palette:
    primary: teal
  font:
    text: Montserrat
  custom_dir: overrides
  logo: assets/flame.png

extra_css:
  - stylesheets/extra.css

plugins: []

